branches:
  only:
  - dev
language: node_js
sudo: false
node_js: stable
cache:
  directories:
  - node_modules
before_install:
- git config --global user.name "cyio"
- git config --global user.email "ibeceo@gmail.com"
- git clone --branch dev https://github.com/cyio/cyio.github.io.git
install:
- npm install
script:
- npm run docs:build
after_script:
- cd docs/.vuepress/dist
- git init
- git add --all .
- git commit --message "auto deploy"
- git push -f "https://${GITHUB_TOKEN}@${GH_REF}" master
env:
  global:
  - GH_REF: github.com/cyio/cyio.github.io.git
  - secure: YUuusBs+U7XpC+qkSbFHUg+DusBx7s0yuEdzXi65GzDaYt9/jV6q7caJ7djH9eE/na0t6zZ9wERl0B7CMOgCNexpySizO5K8kRBYQut1qOgo2ruNCiNauW5/R7zEqn/8024Kj7ZV3dO2JOh/IDb8OY6acViout5KvfHQYmOhfj4WsIBxEvNTnBZpQGwPdqRL6xGcPjLWVlKcpPYaBlocoVbDm0Dfnllsz/F4vE2C/YjeLt8xzVDlDRjp0Kd6ZeyeEaL6ecg6O6qYoqYLAKfR5Gl3EDp7is9+w0WTvHDPkDCWDDM+QEheoE5ylgTfCYsnNY/mj8CSkhbKCvv6HO4MdcxiHIEqKxsEPVeJfiU1X9Llk6XC9aXxGtUiHAJrhjqngUDQd14jSx6uPLqSdO6NUs5CUtITdN9hj2ZAS18zZ3z3DQwrbzwh9xSHyZDsMf18MVMLPQvR8CNleDvfvUGP6wgIK4craVpZswH7MlYLsDu7SinQFasN3ZzWbTD2ieMkE5zHibxs/8WYgUK8/z6woB3BZAdwUJuaWXD8IWeHeiNF0CQPz+UyZoRrrxSqOrunGx/S8iqNyrmA5SF4Qw6v91C2ozSPdeb8YeZYq8DDOOMNhqdAZbtyQ4BHc6WIfyhcpaD1jb2nmbRimCl/BuMx41df8nSQtiHROzxszt3bk9A=
